### ISSUE TITLE
The OnDrop event does not contain enough information.

### ISSUE THREAD

**Issue by csharptest** [willb335/chessboardjsx#23]
The onDrop signature (source, target) for "spare" pieces drops as:
```
  source = "spare"
  target = "g3"
```
This does not tell a consumer "what" spare piece was dropped on the board.

**Comment by willb335** [comment]
This is an easy fix, perhaps ```source = "spare-wR"```

**Comment by csharptest** [comment]
Yeah :/

Again a structure would have been preferable; however, this would be a breaking change. So either adding a third parameter `(source, target, piece: "wR")` or if that is trouble, then yes I can parse it out.

**Comment by willb335** [comment]
I can look into making this a structure

**Comment by willb335** [comment]
I'm going to hold off on refactoring the position object into a structure.  A few important helper functions, ```fenToObject``` and ```objToFen``` are based on the current ```{ e5: 'wK' }``` format.   I brought these over from chessboard.js and don't want to rewrite them at the moment.  

I will refactor into structures where I can, the position object is the one exception

**Comment by willb335** [comment]
@csharptest let me know if this is a fix

https://github.com/willb335/chessboardjsx/pull/22/commits/5e46859de65c17f20be689d3fecf3370aefbe0c0

**Comment by csharptest** [comment]
@willb335 Sounds good, as I said I'm unfamiliar with chessboard.js, so if you are working to make things consistent with that I can understand.

**Comment by willb335** [comment]
The following commit restructures onDrop to have a piece property:  ```onDrop({ sourceSquare, targetSquare, piece })```. 

https://github.com/willb335/chessboardjsx/pull/22/commits/42c1ddfd7eec4db818c173b4bd9cd9152181b05e
