### ISSUE TITLE
Bug: board won't update if game's first move is a CPU move

### ISSUE THREAD

**Issue by furrykef** [willb335/chessboardjsx#29]
Let's say you have a CPU vs. CPU match, like in the Random vs. Random demo in Demo.js. If you watch that demo carefully, you'll notice that white's first move does not register until black makes a move; they appear to move at about the same time. This is much more obvious if you [increase the time between moves to 5 seconds](https://codesandbox.io/s/w7woq5k1ql). All moves after white's first move do update the board correctly.

For a CPU vs. CPU game, this is only a visual quirk, but CPU vs. human games (where the CPU is white) are unplayable, because it looks like white hasn't moved.

**Comment by willb335** [comment]
I can't reproduce this bug.  I have the browser throttled with a 4x slowdown and a 5000ms space between moves and  black is always moving after white.  

The only quirk I can see(and this is an implementation detail in ```RandomVsRandomGame.js```) is that black's first move is immediately after(does not have the 5000 ms delay) white's first move.  This is an easy fix and is outside the scope of Chessboard.jsx.  
```js
 if(firstMove) {...}
```

for a working demo of a cpu human game see https://www.chessboardjsx.com/integrations/stockfish

**Comment by furrykef** [comment]
Black's first move appears immediately after white's move because white's move isn't registering until black moves. White's piece does indeed seem to move first, but it still won't move at all until it receives black's move.

The Stockfish demo has the human play as white and the computer as black, so it won't exhibit the issue. It should if you reverse the colors so that Stockfish has to make the first move.

**Comment by furrykef** [comment]
I think I've made this bug too specific. The more general bug is something like, a change to the `position` property will be ignored if all of the following are true:
- It is the very first change to the property after the component was constructed.
- Only one piece has moved.
- The user has not dragged a piece.

I've made [a demo](https://codesandbox.io/s/qk02z96rzw) that demonstrates this. It's supposed to display this sequence, each position appearing 3 seconds apart:
- The starting position
- The position after 1.e4
- The Lucena position
- A back rank mate

However, what will happen is it will display the starting position for 6 seconds, then the Lucena position for 3 seconds, and finally the back rank mate. The 1.e4 position gets skipped over.

If you change the FEN in the routine for timer1 so that it differs by more than one piece, such as moving both the d- and e-pawns, it will display fine.

**Comment by willb335** [comment]
Ok, I think the root of this is in the ```index.js``` file in ```Chessboard```.  I have it written so positions are only compared when the ```previousPosition``` is not null.  I'll work this out

**Comment by willb335** [comment]
#32

**Comment by willb335** [comment]
#32 

Take a look at the most recent commit and try it with Demo.js.  FYI, when feeding the ```position``` prop make sure to give it a little buffer for transition time
