### ISSUE TITLE
Small bug in RandomVsRandom.componentWillUnmount

### ISSUE THREAD

**Issue by furrykef** [willb335/chessboardjsx#31]
RandomVsRandom.componentWillUnmount has the line `window.clearTimeout(this.timer())`. Surely that should be `this.timer`, without the parentheses? Here's a fixed version: https://codesandbox.io/s/9q198jzz3w

This bug also exists in the git repository.

**Comment by willb335** [comment]
```js
timer = () => window.setTimeout(this.makeRandomMove, 1000);
clearTimeout(timer())

```

timer is a function so I believe it's correct to call it with parenthesis

if it wasn't a function
```js
timer = window.setTimeout(this.makeRandomMove, 1000);
clearTimeout(timer)

```
