### ISSUE TITLE
Updating the position of only one piece outside `onDrop` doesn't update the UI

### ISSUE THREAD

**Issue by slig** [willb335/chessboardjsx#35]
Hi,

I've forked one demo here with this possible bug reproduced https://codesandbox.io/s/kxqxo8lwo3 

One second after manually making a move (`WithMoveValidation.js` lines 80-89), it calls `this.chess.undo()` and updates the state. But somehow, as far as I could tell, `getDerivedStateFromProps` returns `null` to that change and now the internal state and the displayed board are different. (Try moving a white piece, waiting a second, and then moving another white piece)

Thank you very much and please let me know if you need any more details or a better bug report.

**Comment by willb335** [comment]
Check out the fork of your demo below.  I believe it was an async issue with setState.  I changed
```javascript
this.setState(...)
setTimeout(this.setState(...), 1000)
```

to 

```javascript
this.setState(..., () => setTimeout(this.setState(...), 1000) )
```

just put the setTimeout into the initial setState's callback.

let me know if this solves the issue
https://codesandbox.io/s/2xpxvq06wj

**Comment by slig** [comment]
Hi!

Thank you for checking this issue.

On my end I'm still seeing the same problem. Opening the Dev Console, I see that it prints the fen correctly, but the UI stills shows the older state.

Here for instance I moved Kg2, and I'm hovering the f2 pawn:

<img width="359" alt="screen shot 2018-10-09 at 09 08 34" src="https://user-images.githubusercontent.com/37779/46668619-4e62b680-cba3-11e8-80b2-7dd47c13c1e7.png">

Thank you very much!

**Comment by willb335** [comment]
Ok, thanks

I'm looking into it now.

**Comment by willb335** [comment]
going to have to figure this out later today.  it's a bug with how the board his handling the prevState and currentState

**Comment by willb335** [comment]
*prevPos and currentPos

**Comment by willb335** [comment]
I'm going to expose a new prop called ```undo``` to fix this for now. 

I wrote the chessboard to compare positions only if the current position is different than the previous position and when the current position becomes the previous position then there is no comparing.  

I'll try to code up a demo sometime soon

**Comment by willb335** [comment]
Check out this branch : https://github.com/willb335/chessboardjsx/tree/undo
Run ```npm run start```
Click the Undo demo

In the demo I set all pieces except the knights to 'undo' by specifying an ```undo``` prop

Wish I could have integrated a fix without an extra prop but couldn't see an easy way without a substantial rewrite.

Let me know if this works!

**Comment by slig** [comment]
Thank you very much! Will try and get back to you.

**Comment by slig** [comment]
Just tested and this works. Thank you for working on this fix!

**Comment by willb335** [comment]
great! i'll update the docs and push up a new release soon

**Comment by willb335** [comment]
closed by:
2fff88a298bca4e8a67da9d4a3e25e9b1b4c7765
