### ISSUE TITLE
Usage with React Native

### ISSUE THREAD

**Issue by ronlaniado** [willb335/chessboardjsx#36]
I'd like to use this library with React Native, but when I try to, I get:

`Invariant Violation: View config not found for name div. Make sure to start component names with a capital letter.`

I'm assuming this is because this is made for ReactJS? Would it be possible to add support for RN, or is there a way of solving this that I'm not aware of?

**Comment by willb335** [comment]
Hello,
This library only works with the web.  If you want to make a mobile app with this library I would recommend a [PWA](https://developers.google.com/web/progressive-web-apps/) 

Sorry about that

**Comment by ronlaniado** [comment]
Alright, thanks for the help.
