### ISSUE TITLE
onDrop with sparePieces

### ISSUE THREAD

**Issue by claudioluciano** [willb335/chessboardjsx#44]
When using `sparePieces={true}` and try to put a spare piece on the board 
i get this error
`Uncaught TypeError: s is not a function
    at Object.endDrag (chessboard.min.js:2478)
    at t.value (chessboard.min.js:6563)
    at e.t.endDrag (chessboard.min.js:314)
    at Object.r.<computed> [as endDrag] (chessboard.min.js:8169)
    at e.handleTopDragEndCapture (chessboard.min.js:5998)`

when is not a spare piece works fine

**Comment by willb335** [comment]
Can you try using the ```id``` prop for the board?

**Comment by claudioluciano** [comment]
Same problem

**Comment by willb335** [comment]
ok, I'm going to need some more info to try to solve this.  Can you post the code of your chessboard and any code that renders the chessboard?

**Comment by claudioluciano** [comment]
Hey Will here a working exemple of the bug, https://codesandbox.io/s/cool-rain-6jwdp just open the browser console and try put a spare piece on the board

**Comment by willb335** [comment]
It's working as it should for me.  Strange, I'm on a mac running codesandbox with chrome.  That's bizarre

**Comment by claudioluciano** [comment]
No way, it's working on chrome, firefox and safari, but on Opera is not working

**Comment by claudioluciano** [comment]
Hey Will sorry, i think the link above is wrong, this is the right link https://codesandbox.io/s/great-payne-9dzd8, for the bug work you need the onDrop function...

**Comment by willb335** [comment]
Could you checkout the ```spareOnDrop``` branch and run ```yarn start```.  Then click the 'Show Spare OnDrop' button to run the demo.  You can change the demo code at ```integrations/SpareOnDrop```

**Comment by claudioluciano** [comment]
hey Will nice work, the branch spareOnDrop works fine : D

**Comment by willb335** [comment]
ok, nice.  fixed with 6a7b2b8
