### ISSUE TITLE
Next js support?

### ISSUE THREAD

**Issue by DanielJ06** [willb335/chessboardjsx#60]
I tried to use with next recently, and got the error "window not defined". Any idea how to solve?

**Comment by willb335** [comment]
I would add a contdition check ```if (window === undefined) { return null } else {return <Chessboard /> }```.
Chessboardjsx has a dependency on the ```window``` object and when Next is building it does not have access to ```window```.

**Comment by DanielJ06** [comment]
Got it. It is a very cool lib, and it is sad that it is no longer maintained, do you have any recommendations for another similar lib?

**Comment by willb335** [comment]
Maybe check out this one: https://github.com/ruilisi/react-chessground

**Comment by DanielJ06** [comment]
I'll take a look. Thank you very much for your attention

**Comment by neatshell** [comment]
Hi @DanielJ06 if can help you, I've solved with these 3 lines of code and still using this wonderful library

```
import dynamic from 'next/dynamic';

const Chessboard = dynamic(() => import('chessboardjsx'), {
  ssr: false  // <- this do the magic ;)
});
```

**Comment by marlongerson** [comment]
> Hi @DanielJ06 if can help you, I've solved with these 3 lines of code and still using this wonderful library
> 
> ```
> import dynamic from 'next/dynamic';
> 
> const Chessboard = dynamic(() => import('chessboardjsx'), {
>   ssr: false  // <- this do the magic ;)
> });
> ```

Thank you so much!

**Comment by withrvr** [comment]
> Hi @DanielJ06 if can help you, I've solved with these 3 lines of code and still using this wonderful library
> 
> ```
> import dynamic from 'next/dynamic';
> 
> const Chessboard = dynamic(() => import('chessboardjsx'), {
>   ssr: false  // <- this do the magic ;)
> });
> ```

thx so much bro .... you are god
