### ISSUE TITLE
How to achieve square styles in the landing page demo?

### ISSUE THREAD

**Issue by huydhoang** [willb335/chessboardjsx#61]
Hi Will, thanks for creating this awesome plug-n-play chessboard!
I'm working on a hobby project and the documentation was great.

But I'm wondering how to achieve the styles such as on chessboardjsx.com?

The default styles didn't look the same.
Please refer to this demo image as an example.

![image](https://github.com/willb335/chessboardjsx/raw/master/src/img/sicilian.png)

**Comment by willb335** [comment]
Hi, could you take a look at the final example with Elvis and Lebron on the website?  There is a rough square prop that is used

**Comment by willb335** [comment]
You would need to customize the roughness and colors to your liking

**Comment by huydhoang** [comment]
I looked at the example code and it seems to use roughjs v2. The api has changed in current v4 so it doesn't compile. But I still worked out a standard board without custom styling.

Thanks for replying!
