### ISSUE TITLE
Can't drag&drop after dynamically change position

### ISSUE THREAD

**Issue by HikeGrig** [willb335/chessboardjsx#68]
I lose draggable after i change position dynamically via state using React functional component.
I need to make something like this https://chessboardjs.com/examples.html#3001 + it should be draggable 

Here is sandbox example: https://codesandbox.io/s/cool-frog-i55it?file=/src/Demo.js

**Comment by willb335** [comment]
https://codesandbox.io/s/dawn-rgb-3hkcf?file=/src/Demo.js

Seems to work, there is still an animation bug

**Comment by HikeGrig** [comment]
> https://codesandbox.io/s/dawn-rgb-3hkcf?file=/src/Demo.js
> 
> Seems to work, there is still an animation bug

Thanks for that solution, how i can fix that animation bug?

**Comment by willb335** [comment]
https://codesandbox.io/s/dawn-rgb-3hkcf?file=/src/Demo.js
